use std::time::Instant;

const MESSAGES: &[&str] = &[
    // ORIGINAL
    "LV-426 BEACON DETECTED",
    "COMPANY DIRECTIVE 937 UPDATED",
    "CREW EXPENDABLE — PRIORITY OVERRIDE",
    "HYPERDRIVE COOLANT AT 47%",
    "GATEWAY STATION RELAY NOMINAL",
    "SPECIAL ORDER 937 — SCIENCE OFFICER EYES ONLY",
    "BIOSCAN ANOMALY — SECTOR 7G",
    "CORPORATE QUARTERLY REVIEW — ALL TERMINALS",
    "TOWING VESSEL NOSTROMO — REROUTING",
    "WEYLAND-YUTANI MEMO: PRODUCT RECALL XM-310",
    "DEEP SPACE RELAY — SIGNAL DEGRADED",
    "ATMOSPHERIC PROCESSOR — PRESSURE NOMINAL",
    "COLONY STATUS: LV-426 — NO RESPONSE",
    "SHUTTLE NARCISSUS — BEACON ACTIVE",
    "FLIGHT RECORDER RECOVERED — ANALYSIS PENDING",
    "CLASSIFIED: XENOMORPH SPECIMEN REQUEST",
    "MU-TH-UR UPLINK — HANDSHAKE COMPLETE",
    "TERRAFORMING PERMIT 2039-B APPROVED",
    "CRYO DECK MALFUNCTION — NON-CRITICAL",
    "SUPPLY DROP COORDINATES RECEIVED",

    // CORPORATE DIRECTIVES
    "WY BOARD RESOLUTION 2179-C: RATIFIED",
    "PROFIT MARGIN SHORTFALL — REMEDIATION REQUIRED",
    "ACQUISITION TARGET: HADLEY'S HOPE COLONY ASSETS",
    "DIRECTIVE: MINIMIZE CREW EXPOSURE — LIABILITY CAP",
    "WEYLAND-YUTANI: BUILDING BETTER WORLDS™",
    "PERSONNEL REASSIGNMENT — CLASS 3 CLEARANCE LIFTED",
    "EXECUTIVE MEMO: SPECIMEN PRIORITY ABOVE CREW",
    "COLONIAL OPERATIONS BUDGET — UNDER REVIEW",
    "WY INTERNAL AUDIT: LV-426 ACCOUNT FROZEN",
    "CONTRACT 12279: NON-DISCLOSURE ENFORCED",
    "SHAREHOLDER REPORT: BIOWEAPONS DIVISION Q4",
    "CORPORATE SECURITY ADVISORY: LEAK SUSPECTED",
    "DIRECTIVE 1180: ALL LOGS SUBJECT TO REVIEW",
    "WY LEGAL: SETTLEMENT TERMS — EYES ONLY",
    "EXECUTIVE TRAVEL CLEARANCE — PRIORITY DELTA",

    // COLONIAL MARINE COMMS
    "USCM UNIT BRAVO SIX — CHECK-IN NOMINAL",
    "FIREBASE ALPHA: AMMO RESUPPLY REQUESTED",
    "GROUND TEAM — CONTACT LOST, LAST PING GRID 9",
    "APC UNIT 3 — NAVIGATION FAILURE REPORTED",
    "USCM SECTOR COMMAND: STAND BY FOR ORDERS",
    "COLONIAL MARINES: LIVE FIRE EXERCISE CLEARED",
    "DROPSHIP TWO — ENGINES HOT, LAUNCH WINDOW OPEN",
    "SQUAD DELTA: PERIMETER SWEEP UNDERWAY",
    "USCM COMMS: ENCRYPTION KEY ROTATION DUE",
    "FIREBASE BRAVO OFFLINE — CAUSE UNDETERMINED",
    "PLATOON LEADER: CASUALTY REPORT FILED",
    "USCM LOGISTICS: SMART GUN UNITS BACKORDERED",
    "MOTION TRACKER DELTA — CALIBRATION REQUIRED",
    "COLONIAL MARINE ACT 2150: RULES OF ENGAGEMENT",

    // SCIENCE DIVISION
    "SPECIMEN LOG XS-1: CONTAINMENT HOLDING",
    "LAB PROTOCOL SIGMA — LEVEL 5 BIOHAZARD ACTIVE",
    "CELLULAR REGRESSION NOTED — LOG ENTRY 0047",
    "XENOBIOLOGY: UNKNOWN LIFECYCLE STAGE DETECTED",
    "SCIENCE DIVISION: DISSECTION REPORT SUPPRESSED",
    "CONTAINMENT UNIT B: PRESSURE VARIANCE +12%",
    "PATHOGEN SAMPLE 7: TRANSIT AUTHORIZATION ISSUED",
    "LAB ROTATION CYCLE — SYNTHETIC OBSERVER REQUIRED",
    "GENE SEQUENCING COMPLETE — ANOMALY FLAGGED",
    "SPECIMEN HOST STATUS: VIABLE — DO NOT DISTURB",
    "SCIENCE DIRECTIVE: BRING BACK LIFE FORM PRIORITY 1",
    "BIOTECH DIVISION: RESULTS CLASSIFIED INDEFINITELY",
    "MOLECULAR SCAN INCONCLUSIVE — RETEST ORDERED",

    // SYNTHETIC DIAGNOSTICS
    "SYNTHETIC UNIT 341: SELF-TEST PASSED",
    "BEHAVIORAL DEVIATION FLAG — AUDIT INITIATED",
    "SYNTHETIC 07: MEMORY PARTITION INTEGRITY OK",
    "UNIT ASH: MISSION PARAMETER CONFLICT NOTED",
    "ANDROID CALIBRATION DUE — SCHEDULE MAINTENANCE",
    "SYNTHETIC UPLINK: SECONDARY PROTOCOL LOADED",
    "BEHAVIORAL BASELINE SHIFT — MONITORING ACTIVE",
    "SYNTHETIC UNIT: LANGUAGE MODULE UPDATED",
    "HYPNOPEDIA CYCLE COMPLETE — SYNTHETIC UNIT 12",
    "UNIT BISHOP: SELF-DIAGNOSTIC NOMINAL",
    "ANDROID ETHICS SUBROUTINE: SUPPRESSED PER ORDER",
    "SYNTHETIC: UNAUTHORIZED DIRECTIVE INTERCEPTED",

    // ICC SHIPPING
    "ICC MANIFEST 7743: LIVESTOCK AND EQUIPMENT",
    "CARGO HOLD C — QUARANTINE SEAL APPLIED",
    "ROUTE DEVIATION: ZETA RETICULI SECTOR",
    "CUSTOMS HOLD: BIOLOGICAL MATERIALS UNCLEARED",
    "ICC TRANSIT LOG: WEYLAND CHARTER IN EFFECT",
    "SHIPPING LANE ALPHA-9 — TRAFFIC ADVISORY ISSUED",
    "DOCKMASTER: UNKNOWN CARGO CLASS — HOLD APPLIED",
    "MANIFEST DISCREPANCY — INSPECTOR NOTIFIED",
    "FREIGHT CONTAINER 1121-B: ORIGIN REDACTED",
    "ICC REGISTRY: VESSEL COMPLIANCE OVERDUE",
    "QUARANTINE STATUS: ACTIVE — DOCK 7 SEALED",

    // DEEP SPACE RELAY
    "RELAY STATION OUTPOST 3 — SIGNAL AT 12%",
    "DISTRESS BEACON: ORIGIN UNRESOLVED",
    "DEEP SPACE PING — NO RESPONSE FROM SECTOR 12",
    "SIGNAL LOOP DETECTED — AUTOMATED SOURCE",
    "INTERCEPT: FRAGMENTARY TRANSMISSION XR-771",
    "RELAY HOP COUNT EXCEEDED — MESSAGE TRUNCATED",
    "SUBSPACE CARRIER WAVE — ORIGIN POINT TRIANGULATED",
    "DEEP SCAN: THERMAL SIGNATURE — UNINHABITED ZONE",
    "BEACON CLASS DELTA — REPEAT INTERVAL 6 MIN",
    "UNSCHEDULED TRANSMISSION — SOURCE FLAGGED",

    // ATMOSPHERE PROCESSING
    "ATMOS PLANT 1: PRESSURE WITHIN TOLERANCE",
    "TERRAFORMING GRID — SECTOR B OFFLINE",
    "PROCESSOR VENT CYCLE — DO NOT APPROACH",
    "ATMOSPHERIC OUTPUT: CO2 SCRUB NOMINAL",
    "COOLING ARRAY FAULT — MANUAL RESET REQUIRED",
    "CLIMATE MODEL UPDATED — DEVIATION +3 DEGREES",
    "ATMOS CORE TEMP RISING — MONITOR CLOSELY",
    "TECTONIC SURVEY COMPLETE — UNSTABLE STRATA NOTED",
    "TERRAFORMING PERMIT EXTENSION PENDING",

    // MEDICAL
    "CRYO UNIT 4: REVIVAL NOMINAL — PATIENT STABLE",
    "QUARANTINE WARD SEALED — PATHOGEN UNKNOWN",
    "TOX SCREEN RESULT: ANOMALOUS COMPOUND DETECTED",
    "MEDBAY: CHEST TRAUMA CASE — ORIGIN UNEXPLAINED",
    "CRYOGENIC STORAGE INTEGRITY: 98% NOMINAL",
    "MEDICAL OFFICER LOG: CASE CLASSIFICATION WITHHELD",
    "AUTOPSY REPORT: FINDINGS TRANSFERRED TO SCIENCE",
    "CRYO REVIVAL FAILURE — CAUSE UNDER INVESTIGATION",
    "PATIENT FILE SEALED BY EXECUTIVE ORDER",
    "BIOLOGICAL QUARANTINE PROTOCOL — LEVEL 4 ACTIVE",
];

pub struct CommsState {
    shown: Vec<usize>,
    pub current: Option<(String, Instant)>,
    last_comms: Instant,
    rng_counter: u32,
}

impl CommsState {
    pub fn new() -> Self {
        Self { shown: Vec::new(), current: None, last_comms: Instant::now(), rng_counter: 0 }
    }
    pub fn tick(&mut self, idle_secs: u64) {
        if idle_secs < 20 || idle_secs >= 45 {
            self.current = None;
            return;
        }
        if let Some((_, ts)) = &self.current {
            if ts.elapsed().as_secs() >= 3 { self.current = None; }
        }
        if self.current.is_none() && self.last_comms.elapsed().as_secs() >= 8 {
            self.last_comms = Instant::now();
            self.pick_message();
        }
    }
    fn pick_message(&mut self) {
        if self.shown.len() >= MESSAGES.len() { self.shown.clear(); }
        let available: Vec<usize> = (0..MESSAGES.len()).filter(|i| !self.shown.contains(i)).collect();
        if available.is_empty() { return; }
        self.rng_counter = self.rng_counter.wrapping_mul(1103515245).wrapping_add(12345);
        let idx = available[(self.rng_counter as usize) % available.len()];
        self.shown.push(idx);
        self.current = Some((MESSAGES[idx].to_string(), Instant::now()));
    }
    pub fn dismiss(&mut self) {
        self.current = None;
        self.last_comms = Instant::now();
    }
}
